Repository Alfresco/alfresco-android-app, pull requests merged in 2018-03, with the labels that each got.

#458 ANDROID-572 Support SAML in Android Document Provider
  alfresco-mobile-android/src/main/java/org/alfresco/mobile/android/application/providers/storage/StorageAccessDocumentsProvider.java
Labels: enhancement

#459 ANDROID-582 Crash on attempt to open Site after attempt to update file in offline mode using Word
  alfresco-mobile-android/src/main/java/org/alfresco/mobile/android/application/providers/storage/StorageAccessDocumentsProvider.java
Labels: bug

#460 ANDROID-572 Support SAML auth in Android Document Provider
  alfresco-mobile-android/src/main/java/org/alfresco/mobile/android/application/providers/storage/StorageAccessDocumentsProvider.java
Labels: enhancement

#461 ANDROID-572 Added missing string resource
  platform/foundation/src/main/res/values/alfresco_strings.xml
Labels: bug

#462 ANDROID-572 added another check for stale session
  alfresco-mobile-android/src/main/java/org/alfresco/mobile/android/application/providers/storage/StorageAccessDocumentsProvider.java
Labels: bug

#463 ANDROID-572 added a fix for when the app is closed and the account is SAML type
  alfresco-mobile-android/src/main/java/org/alfresco/mobile/android/application/providers/storage/StorageAccessDocumentsProvider.java
Labels: bug

#464 ANDROID-585 Update Minimum Android version to 4.4
  alfresco-mobile-android/build.gradle
Labels: enhancement

#465 Fixed a session problem and updated the error message
  alfresco-mobile-android/src/main/java/org/alfresco/mobile/android/application/providers/storage/StorageAccessDocumentsProvider.java
  platform/foundation/src/main/res/values/alfresco_strings.xml
Labels: bug, enhancement

#466 ANDROID-572 Safety checked all the sessions inside the document provider
  alfresco-mobile-android/src/main/java/org/alfresco/mobile/android/application/providers/storage/StorageAccessDocumentsProvider.java
Labels: bug

#467 ANDROID-589 Update the UI string re: ANDROID-572
  platform/foundation/src/main/res/values/alfresco_strings.xml
Labels: enhancement

#469 ANDROID-591 Update the UI text in the About screen
  alfresco-mobile-android/src/main/res/values/strings.xml
Labels: enhancement

#470 ANDROID-578 Added localization for the unlocalized strings
  alfresco-mobile-android/src/main/res/values-de/strings.xml
  alfresco-mobile-android/src/main/res/values-es/strings.xml
  alfresco-mobile-android/src/main/res/values-fr/strings.xml
  alfresco-mobile-android/src/main/res/values-it/strings.xml
  alfresco-mobile-android/src/main/res/values-ja/strings.xml
  alfresco-mobile-android/src/main/res/values-zh-rCN/strings.xml
  platform/foundation/src/main/res/values-de/alfresco_strings.xml
  platform/foundation/src/main/res/values-es/alfresco_strings.xml
  platform/foundation/src/main/res/values-fr/alfresco_strings.xml
  platform/foundation/src/main/res/values-it/alfresco_strings.xml
  platform/foundation/src/main/res/values-ja/alfresco_strings.xml
  platform/foundation/src/main/res/values-zh-rCN/alfresco_strings.xml
Labels: enhancement
